theme: minima

include: 
  - assets/css/styles.css
  
title: SeeRise

plugins:
  - jekyll-theme

header_pages:
  - index.md
  - about.md
  - figures.md
  - app.md

author: Eric Pham, Ylesia Wu, & Zoe Ludena
